live_config_reload = true

[shell]
args    = ["--login", "-c", "tmux attach || tmux"]
program = "/bin/zsh"

[window]
decorations        = "none"
startup_mode       = "Maximized"
dimensions.lines   = 0
dimensions.columns = 0
padding.x          = 0
padding.y          = 0

[scrolling]
history = 0

[font]
size          = 18.0
offset.y      = -3
normal.family = "Iosevka"

[colors]
primary.background = "#000000"
primary.foreground = "#d8d7d7"
normal.black       = "#555555"
normal.blue        = "#5eabd3"
normal.cyan        = "#60d7af"
normal.green       = "#afd75f"
normal.magenta     = "#af87d7"
normal.red         = "#d15c5c"
normal.white       = "#d8d7d7"
normal.yellow      = "#d1d05c"

[keyboard]
bindings = [
  { key = "I",         chars = "\u001B[105;5u", mods = "Control"       },
  { key = "Return",    chars = "\u001B[13;2u",  mods = "Shift"         },
  { key = "Return",    chars = "\u001B[13;5u",  mods = "Control"       },
  { key = "Return",    chars = "\u001B[13;6u",  mods = "Control|Shift" },
  { key = "A",         chars = "\u001B[65;6u",  mods = "Control|Shift" },
  { key = "B",         chars = "\u001B[66;6u",  mods = "Control|Shift" },
  { key = "C",         chars = "\u001B[67;6u",  mods = "Control|Shift" },
  { key = "D",         chars = "\u001B[68;6u",  mods = "Control|Shift" },
  { key = "E",         chars = "\u001B[69;6u",  mods = "Control|Shift" },
  { key = "F",         chars = "\u001B[70;6u",  mods = "Control|Shift" },
  { key = "G",         chars = "\u001B[71;6u",  mods = "Control|Shift" },
  { key = "H",         chars = "\u001B[72;6u",  mods = "Control|Shift" },
  { key = "I",         chars = "\u001B[73;6u",  mods = "Control|Shift" },
  { key = "J",         chars = "\u001B[74;6u",  mods = "Control|Shift" },
  { key = "K",         chars = "\u001B[75;6u",  mods = "Control|Shift" },
  { key = "L",         chars = "\u001B[76;6u",  mods = "Control|Shift" },
  { key = "M",         chars = "\u001B[77;6u",  mods = "Control|Shift" },
  { key = "N",         chars = "\u001B[78;6u",  mods = "Control|Shift" },
  { key = "O",         chars = "\u001B[79;6u",  mods = "Control|Shift" },
  { key = "P",         chars = "\u001B[80;6u",  mods = "Control|Shift" },
  { key = "Q",         chars = "\u001B[81;6u",  mods = "Control|Shift" },
  { key = "R",         chars = "\u001B[82;6u",  mods = "Control|Shift" },
  { key = "S",         chars = "\u001B[83;6u",  mods = "Control|Shift" },
  { key = "T",         chars = "\u001B[84;6u",  mods = "Control|Shift" },
  { key = "U",         chars = "\u001B[85;6u",  mods = "Control|Shift" },
  { key = "V",         chars = "\u001B[86;6u",  mods = "Control|Shift" },
  { key = "W",         chars = "\u001B[87;6u",  mods = "Control|Shift" },
  { key = "X",         chars = "\u001B[88;6u",  mods = "Control|Shift" },
  { key = "Y",         chars = "\u001B[89;6u",  mods = "Control|Shift" },
  { key = "Z",         chars = "\u001B[90;6u",  mods = "Control|Shift" },
  { key = "Key1",      chars = "\u001B[49;6u",  mods = "Control|Shift" },
  { key = "Key2",      chars = "\u001B[50;6u",  mods = "Control|Shift" },
  { key = "Key3",      chars = "\u001B[51;6u",  mods = "Control|Shift" },
  { key = "Key4",      chars = "\u001B[52;6u",  mods = "Control|Shift" },
  { key = "Key5",      chars = "\u001B[53;6u",  mods = "Control|Shift" },
  { key = "Key6",      chars = "\u001B[54;6u",  mods = "Control|Shift" },
  { key = "Key7",      chars = "\u001B[55;6u",  mods = "Control|Shift" },
  { key = "Key8",      chars = "\u001B[56;6u",  mods = "Control|Shift" },
  { key = "Key9",      chars = "\u001B[57;6u",  mods = "Control|Shift" },
  { key = "Key0",      chars = "\u001B[48;6u",  mods = "Control|Shift" },
  { key = "Minus",     chars = "\u001B[45;6u",  mods = "Control|Shift" },
  { key = "Equals",    chars = "\u001B[61;6u",  mods = "Control|Shift" },
  { key = "LBracket",  chars = "\u001B[91;6u",  mods = "Control|Shift" },
  { key = "RBracket",  chars = "\u001B[93;6u",  mods = "Control|Shift" },
  { key = "Backslash", chars = "\u001B[92;6u",  mods = "Control|Shift" },
  { key = "Semicolon", chars = "\u001B[59;6u",  mods = "Control|Shift" },
  { key = "Period",    chars = "\u001B[46;6u",  mods = "Control|Shift" },
  { key = "Slash",     chars = "\u001B[47;6u",  mods = "Control|Shift" },
  { key = "Comma",     chars = "\u001B[44;6u",  mods = "Control|Shift" },
  { key = "`",         chars = "\u001B[96;6u",  mods = "Control|Shift" },
  { key = "'",         chars = "\u001B[39;6u",  mods = "Control|Shift" },
]

